spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matters?useUnicode=true&useSSl=fals@characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/matters/*mapper.xml
  type-aliases-package: com.liuling.matters.entity
logging:
  level:
    com.liuling.matters.dao:trace